skip = [
    "check-python",
    "build-npm",
    "check-npm",
]

[hooks]
before-build-python = ["jlpm clean:all"]
before-bump-version = ["python -m pip install tomlkit"]

[options]
version-cmd = "python ../../scripts/bump-version.py --skip-if-dirty"
python_packages = [
    "packages/jupyter-ai:dkrz-jupyter-ai",
    "packages/jupyter-ai-magics:dkrz-jupyter-ai-magics",
    "packages/jupyter-climateclaw:jupyter-climateclaw",
]
